# Generated by Django 6.0 on 2025-12-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_categoria_rename_creada_tarea_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(blank='True', choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=12, null='True'),
        ),
    ]
